name: build-image
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'key4hep*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase owner name
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{env.OWNER_LC}}/ci-test-dummy
      - name: Build and Push (ci-test)
        id: docker_build_ci-test
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile-helloworld
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=ghcr.io/${{env.OWNER_LC}}
          tags: ghcr.io/${{env.OWNER_LC}}/ci-test-hello:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}